### ISSUE TITLE
TypeError: 'staticmethod' object is not callable

### ISSUE THREAD

**Issue by BrainStone** [Andre0512/speedport-api#1]
Hey, I just tried to install this on my Debian 11 server. When running any command (I tried it with `speedport` and `speedport --help`) I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/speedport", line 5, in <module>
    from speedport.__main__ import start
  File "/usr/local/lib/python3.9/dist-packages/speedport/__init__.py", line 1, in <module>
    from .speedport import Speedport
  File "/usr/local/lib/python3.9/dist-packages/speedport/speedport.py", line 19, in <module>
    class Speedport:
  File "/usr/local/lib/python3.9/dist-packages/speedport/speedport.py", line 129, in Speedport
    async def ip_data(self):
TypeError: 'staticmethod' object is not callable
```

```shell
$ python --version
Python 3.9.2
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by Andre0512** [comment]
Hey, the used syntax seems to be incompatible with python <3.10, should be working now.
Thanks for reporting! :slightly_smiling_face:
